### ISSUE TITLE
部署到服务器时，SSL证书如何导入？

### ISSUE THREAD

**Issue by Yongqi-Liang** [Jinvic/video-chat#1]
部署到服务器时，SSL证书如何导入？

**Comment by Jinvic** [comment]
原项目在[这里](https://github.com/itstaranarora/video-chat-v1)

这只是一个小组作业，我们将其读懂后本地测试成功并讲解后就没有进一步的工作了，也没有部署到服务器上过。

很抱歉不能帮助到你。

**Comment by Yongqi-Liang** [comment]
好的，谢谢
